### PR TITLE
New Rendering header file made for Linux and Mac OS

### PR DESCRIPTION
**Pull request by aswinigh**

### CODE REVIEW

**Comment by archit120** [comment]
Please add Cmake and modified render.h too

**Comment by archit120** [comment]
Please add Cmake and modified render.h too

**Comment by aswinigh** [comment]
> Please add Cmake and modified render.h too

render.h is not modified but a new file called renderlinux.h is used

**Comment by archit120** [comment]
Add that file

**Comment by archit120** [comment]
Shouldn't the cleanup function be in the destructor of screen? Also Cmake files

**Comment by aswinigh** [comment]
> Shouldn't the cleanup function be in the destructor of screen? Also Cmake files

Made the required changes. Some changes maybe required in CMake for it to work on Windows

**Comment by archit120** [comment]
So this looks good and I'll merge it for now. However, can you think of a way to better integrate the screen file to prevent duplication of code? Also for Windows I plan to keep this as a VS project for now because configuring cmake can be hard on Windows.

**Comment by aswinigh** [comment]
> So this looks good and I'll merge it for now. However, can you think of a way to better integrate the screen file to prevent duplication of code? 

That would require external libraries to be added. I will think if there is any other way

**Pull request merged**
